# -*- coding: utf-8 -*-
"""samplebot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuHph6DiB5D5ftSlbY2F3p4MLFtRz395
"""

pip install streamlit

import streamlit as st

# HTML code
html_code = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Basic HTML with Background Color</title>
    <style>
        body {
            background-color: lightblue; /* You can change this to any color you like */
        }
    </style>
</head>
<body>
    <h1>Welcome to My Website</h1>
    <p>This is a basic HTML page with a background color.</p>

    <script src="https://cdn.botpress.cloud/webchat/v1/inject.js"></script>
    <script src="https://mediafiles.botpress.cloud/290ce455-017a-400c-bd35-d848497001f8/webchat/config.js" defer></script>
</body>
</html>
"""

# Render the HTML code in Streamlit
st.markdown(html_code, unsafe_allow_html=True)

